const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.TiledBg,
		C3.Plugins.Sprite,
		C3.Behaviors.solid,
		C3.Behaviors.bound,
		C3.Behaviors.Sin,
		C3.Behaviors.Pin,
		C3.Behaviors.scrollto,
		C3.Behaviors.Platform,
		C3.Plugins.Mouse,
		C3.Plugins.Keyboard,
		C3.Plugins.Audio,
		C3.Behaviors.Anchor,
		C3.Plugins.Text,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Audio.Acts.Stop,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Mouse.Cnds.OnObjectClicked,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Acts.ResetGlobals,
		C3.Behaviors.Pin.Acts.PinByProperties,
		C3.Plugins.Sprite.Acts.StartAnim,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Plugins.Keyboard.Cnds.OnAnyKeyReleased,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.System.Acts.Wait,
		C3.ScriptsInEvents.Folhafase2_Event8_Act3,
		C3.Plugins.Text.Acts.SetText,
		C3.Behaviors.Platform.Cnds.IsFalling,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Behaviors.Platform.Acts.SetVectorY,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Acts.GoToLayoutByName,
		C3.Plugins.System.Acts.AddVar,
		C3.ScriptsInEvents.Folhafase1_Event6_Act3
	];
};
self.C3_JsPropNameTable = [
	{PlanoDeFundoEmBlocos: 0},
	{Sólido: 0},
	{chão: 0},
	{RestritoAoLayout: 0},
	{Senóide: 0},
	{inimigo: 0},
	{pedra: 0},
	{Fixar: 0},
	{CentrarEm: 0},
	{jogador: 0},
	{Plataforma: 0},
	{colisao: 0},
	{Mouse: 0},
	{Teclado: 0},
	{Áudio: 0},
	{Sprite5: 0},
	{Sprite6: 0},
	{Sprite7: 0},
	{colisaoinimigodireita: 0},
	{Âncora: 0},
	{vida: 0},
	{txtvida: 0},
	{Sprite3: 0},
	{Sprite4: 0},
	{Sprite8: 0},
	{PlanoDeFundoEmBlocos4: 0},
	{PlanoDeFundoEmBlocos8: 0},
	{PlanoDeFundoEmBlocos10: 0},
	{btnstart: 0},
	{colisaoinimigoesquerda: 0},
	{PlanoDeFundoEmBlocos2: 0},
	{yes: 0},
	{No: 0},
	{cristais: 0},
	{Sprite2: 0},
	{Sprite: 0},
	{Sprite9: 0},
	{Sprite10: 0},
	{Sprite11: 0},
	{Sprite12: 0},
	{Sprite14: 0},
	{inimigo2: 0},
	{PlanoDeFundoEmBlocos3: 0},
	{Sprite13: 0},
	{Sprite15: 0},
	{Sprite16: 0},
	{PlanoDeFundoEmBlocos5: 0},
	{PlanoDeFundoEmBlocos6: 0},
	{cristais2: 0},
	{txtcristal: 0},
	{vidas2: 0},
	{vidas: 0},
	{cristal: 0}
];

self.InstanceType = {
	PlanoDeFundoEmBlocos: class extends self.ITiledBackgroundInstance {},
	chão: class extends self.ISpriteInstance {},
	inimigo: class extends self.ISpriteInstance {},
	pedra: class extends self.ISpriteInstance {},
	jogador: class extends self.ISpriteInstance {},
	colisao: class extends self.ISpriteInstance {},
	Mouse: class extends self.IInstance {},
	Teclado: class extends self.IInstance {},
	Áudio: class extends self.IInstance {},
	Sprite5: class extends self.ISpriteInstance {},
	Sprite6: class extends self.ISpriteInstance {},
	Sprite7: class extends self.ISpriteInstance {},
	colisaoinimigodireita: class extends self.ISpriteInstance {},
	vida: class extends self.ISpriteInstance {},
	txtvida: class extends self.ITextInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	Sprite8: class extends self.ISpriteInstance {},
	PlanoDeFundoEmBlocos4: class extends self.ITiledBackgroundInstance {},
	PlanoDeFundoEmBlocos8: class extends self.ITiledBackgroundInstance {},
	PlanoDeFundoEmBlocos10: class extends self.ITiledBackgroundInstance {},
	btnstart: class extends self.ISpriteInstance {},
	colisaoinimigoesquerda: class extends self.ISpriteInstance {},
	PlanoDeFundoEmBlocos2: class extends self.ITiledBackgroundInstance {},
	yes: class extends self.ISpriteInstance {},
	No: class extends self.ISpriteInstance {},
	cristais: class extends self.ISpriteInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	Sprite: class extends self.ISpriteInstance {},
	Sprite9: class extends self.ISpriteInstance {},
	Sprite10: class extends self.ISpriteInstance {},
	Sprite11: class extends self.ISpriteInstance {},
	Sprite12: class extends self.ISpriteInstance {},
	Sprite14: class extends self.ISpriteInstance {},
	inimigo2: class extends self.ISpriteInstance {},
	PlanoDeFundoEmBlocos3: class extends self.ITiledBackgroundInstance {},
	Sprite13: class extends self.ISpriteInstance {},
	Sprite15: class extends self.ISpriteInstance {},
	Sprite16: class extends self.ISpriteInstance {},
	PlanoDeFundoEmBlocos5: class extends self.ITiledBackgroundInstance {},
	PlanoDeFundoEmBlocos6: class extends self.ITiledBackgroundInstance {},
	cristais2: class extends self.ISpriteInstance {},
	txtcristal: class extends self.ITextInstance {}
}